# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/louis/Projects/UPC/A/FIB-A-CryptoHash

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/louis/Projects/UPC/A/FIB-A-CryptoHash

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/louis/Projects/UPC/A/FIB-A-CryptoHash/CMakeFiles /home/louis/Projects/UPC/A/FIB-A-CryptoHash/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/louis/Projects/UPC/A/FIB-A-CryptoHash/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named utils

# Build rule for target.
utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 utils
.PHONY : utils

# fast build rule for target.
utils/fast:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/build
.PHONY : utils/fast

#=============================================================================
# Target rules for targets named experiments

# Build rule for target.
experiments: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 experiments
.PHONY : experiments

# fast build rule for target.
experiments/fast:
	$(MAKE) -f CMakeFiles/experiments.dir/build.make CMakeFiles/experiments.dir/build
.PHONY : experiments/fast

#=============================================================================
# Target rules for targets named cryptohash.exe

# Build rule for target.
cryptohash.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cryptohash.exe
.PHONY : cryptohash.exe

# fast build rule for target.
cryptohash.exe/fast:
	$(MAKE) -f CMakeFiles/cryptohash.exe.dir/build.make CMakeFiles/cryptohash.exe.dir/build
.PHONY : cryptohash.exe/fast

src/BloomFilter.o: src/BloomFilter.cc.o

.PHONY : src/BloomFilter.o

# target to build an object file
src/BloomFilter.cc.o:
	$(MAKE) -f CMakeFiles/cryptohash.exe.dir/build.make CMakeFiles/cryptohash.exe.dir/src/BloomFilter.cc.o
.PHONY : src/BloomFilter.cc.o

src/BloomFilter.i: src/BloomFilter.cc.i

.PHONY : src/BloomFilter.i

# target to preprocess a source file
src/BloomFilter.cc.i:
	$(MAKE) -f CMakeFiles/cryptohash.exe.dir/build.make CMakeFiles/cryptohash.exe.dir/src/BloomFilter.cc.i
.PHONY : src/BloomFilter.cc.i

src/BloomFilter.s: src/BloomFilter.cc.s

.PHONY : src/BloomFilter.s

# target to generate assembly for a file
src/BloomFilter.cc.s:
	$(MAKE) -f CMakeFiles/cryptohash.exe.dir/build.make CMakeFiles/cryptohash.exe.dir/src/BloomFilter.cc.s
.PHONY : src/BloomFilter.cc.s

src/experiments/src/ExpExample.o: src/experiments/src/ExpExample.cc.o

.PHONY : src/experiments/src/ExpExample.o

# target to build an object file
src/experiments/src/ExpExample.cc.o:
	$(MAKE) -f CMakeFiles/experiments.dir/build.make CMakeFiles/experiments.dir/src/experiments/src/ExpExample.cc.o
.PHONY : src/experiments/src/ExpExample.cc.o

src/experiments/src/ExpExample.i: src/experiments/src/ExpExample.cc.i

.PHONY : src/experiments/src/ExpExample.i

# target to preprocess a source file
src/experiments/src/ExpExample.cc.i:
	$(MAKE) -f CMakeFiles/experiments.dir/build.make CMakeFiles/experiments.dir/src/experiments/src/ExpExample.cc.i
.PHONY : src/experiments/src/ExpExample.cc.i

src/experiments/src/ExpExample.s: src/experiments/src/ExpExample.cc.s

.PHONY : src/experiments/src/ExpExample.s

# target to generate assembly for a file
src/experiments/src/ExpExample.cc.s:
	$(MAKE) -f CMakeFiles/experiments.dir/build.make CMakeFiles/experiments.dir/src/experiments/src/ExpExample.cc.s
.PHONY : src/experiments/src/ExpExample.cc.s

src/main.o: src/main.cc.o

.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) -f CMakeFiles/cryptohash.exe.dir/build.make CMakeFiles/cryptohash.exe.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) -f CMakeFiles/cryptohash.exe.dir/build.make CMakeFiles/cryptohash.exe.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) -f CMakeFiles/cryptohash.exe.dir/build.make CMakeFiles/cryptohash.exe.dir/src/main.cc.s
.PHONY : src/main.cc.s

src/utils/src/RandomString.o: src/utils/src/RandomString.cc.o

.PHONY : src/utils/src/RandomString.o

# target to build an object file
src/utils/src/RandomString.cc.o:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils/src/RandomString.cc.o
.PHONY : src/utils/src/RandomString.cc.o

src/utils/src/RandomString.i: src/utils/src/RandomString.cc.i

.PHONY : src/utils/src/RandomString.i

# target to preprocess a source file
src/utils/src/RandomString.cc.i:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils/src/RandomString.cc.i
.PHONY : src/utils/src/RandomString.cc.i

src/utils/src/RandomString.s: src/utils/src/RandomString.cc.s

.PHONY : src/utils/src/RandomString.s

# target to generate assembly for a file
src/utils/src/RandomString.cc.s:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils/src/RandomString.cc.s
.PHONY : src/utils/src/RandomString.cc.s

src/utils/src/Timer.o: src/utils/src/Timer.cc.o

.PHONY : src/utils/src/Timer.o

# target to build an object file
src/utils/src/Timer.cc.o:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils/src/Timer.cc.o
.PHONY : src/utils/src/Timer.cc.o

src/utils/src/Timer.i: src/utils/src/Timer.cc.i

.PHONY : src/utils/src/Timer.i

# target to preprocess a source file
src/utils/src/Timer.cc.i:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils/src/Timer.cc.i
.PHONY : src/utils/src/Timer.cc.i

src/utils/src/Timer.s: src/utils/src/Timer.cc.s

.PHONY : src/utils/src/Timer.s

# target to generate assembly for a file
src/utils/src/Timer.cc.s:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils/src/Timer.cc.s
.PHONY : src/utils/src/Timer.cc.s

src/utils/src/sha256.o: src/utils/src/sha256.cc.o

.PHONY : src/utils/src/sha256.o

# target to build an object file
src/utils/src/sha256.cc.o:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils/src/sha256.cc.o
.PHONY : src/utils/src/sha256.cc.o

src/utils/src/sha256.i: src/utils/src/sha256.cc.i

.PHONY : src/utils/src/sha256.i

# target to preprocess a source file
src/utils/src/sha256.cc.i:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils/src/sha256.cc.i
.PHONY : src/utils/src/sha256.cc.i

src/utils/src/sha256.s: src/utils/src/sha256.cc.s

.PHONY : src/utils/src/sha256.s

# target to generate assembly for a file
src/utils/src/sha256.cc.s:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils/src/sha256.cc.s
.PHONY : src/utils/src/sha256.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... utils"
	@echo "... rebuild_cache"
	@echo "... experiments"
	@echo "... cryptohash.exe"
	@echo "... edit_cache"
	@echo "... src/BloomFilter.o"
	@echo "... src/BloomFilter.i"
	@echo "... src/BloomFilter.s"
	@echo "... src/experiments/src/ExpExample.o"
	@echo "... src/experiments/src/ExpExample.i"
	@echo "... src/experiments/src/ExpExample.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils/src/RandomString.o"
	@echo "... src/utils/src/RandomString.i"
	@echo "... src/utils/src/RandomString.s"
	@echo "... src/utils/src/Timer.o"
	@echo "... src/utils/src/Timer.i"
	@echo "... src/utils/src/Timer.s"
	@echo "... src/utils/src/sha256.o"
	@echo "... src/utils/src/sha256.i"
	@echo "... src/utils/src/sha256.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

